= estatio-canonical

This module defines a set of DTOs that represent a stable API for extracting information from an instance of link:http://github.com/estatio/estatio[Estatio application].
The data in these DTOs can then be used for various integration scenarios, eg to co-ordinate with a general ledger system.

The http://github.com/isisaddons/isis-module-publishmq[Isis addons' publishmq] module describes one architecture by which these DTOs may be used:

* the Estatio application publishes action invocations/property edits as messages onto an Apache ActiveMQ queue

* an Apache Camel message bus consumes these messages, and routes the message according to the action/property that was invoked/edited

* a processing bean calls back to Estatio via its link:http://isis.apache.org/guides/ugvro.html[REST API], specifying these DTOs as part of the link:http://isis.apache.org/guides/ugvro.html#_ugvro_ro-spec_extensions_content-negotiation[content negotation] (HTTP `Accept` header).







== Change Log

`2.2.0.yyyyMMdd-HHmm-shaId`::

ECP-948: CodaDocHeads DTO


`2.1.1.yyyyMMdd-HHmm-shaId`::

ECP-936: Fixed Asset DTO


`2.1.1.yyyyMMdd-HHmm-shaId`::

ECP-904: Document list DTO


`2.0.0-M1.yyyyMMdd-HHmm-shaId`::

Switches to continuous releases via gitlab.com, published to `maven` repo on our own Sonatype Nexus @ https://repo.incode.cloud[repo.incode.cloud].
+
[NOTE]
====
This artifact is no longer published to Maven Central.
====


`2.0.0-M1`::

Extends 1.x schemas with some new attributes; adds 2.0 schemas (source compatible with 1.x) that are generated from XSDs.

`1.2.0`::

Updated for Apache Isis 1.16.2, adds Lombok builder support

`1.1.0`::

Updated for Apache Isis 1.14.0


`1.0.0`::

initial version (extracted from the ECP-specific version of Estatio).




== Legal Stuff

=== License

[source]
----
Copyright 2016~date Dan Haywood

Licensed under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
----




== Release Process

Pushing to gitlab.com will trigger a CI build that will automatically publish a timestamped version to the `maven-dev` repo on our own Sonatype Nexus @ https://repo.incode.cloud[repo.incode.cloud].

To promote this to `maven-test` or `maven-prod`, use the scripts in https://gitlab.com/incodehq-public/nexus-scripts[incodehq-public/nexus-scripts] (on gitlab.com).

